# Generated by Django 6.0.4 on 2026-08-31 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTFTeam_Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket_name', models.CharField(max_length=200, unique=True)),
                ('open_bracket', models.BooleanField(default=True)),
                ('access_hash', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ctfteam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ctfteam',
            name='bracket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.ctfteam_bracket'),
        ),
    ]
