services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:z
      - caddy_data:/data
    restart: unless-stopped

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rng

  app:
    build:
      context: .
      args:
        APP: bctf.asgi
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rng

      CTFTIME_OAUTH_CLIENTID: x
      CTFTIME_OAUTH_CLIENTSECRET: x
    depends_on:
      - db
    labels:
      caddy: "https://damctf.xyz"
      caddy.tls: internal
      caddy.1_handle:
      caddy.1_handle.reverse_proxy: "{{upstreams 8000}}"

  api:
    build:
      context: .
      args:
        APP: bctf-api.asgi
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rng
    depends_on:
      - db
    labels:
      caddy: "https://damctf.xyz"
      caddy.0_handle_path: /api/*
      caddy.0_handle_path.reverse_proxy: "{{upstreams 8000}}"

volumes:
  caddy_data:
