FROM python:3.12-alpine

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Disable development dependencies
ENV UV_NO_DEV=1

RUN adduser -S -s /sbin/nologin app

# Sync the project into a new environment, asserting the lockfile is up to date
WORKDIR /app
COPY pyproject.toml uv.lock /app
RUN uv sync --locked

# Copy the project into the image
COPY . /app

USER app
EXPOSE 8001
CMD uv run gunicorn --bind 0.0.0.0:8001 bctf-api.wsgi
