# Generated by Django 6.0.4 on 2026-06-16 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('chal_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('author', models.TextField()),
                ('category', models.TextField()),
                ('description', models.TextField()),
                ('min_points', models.IntegerField()),
                ('max_points', models.IntegerField()),
                ('flag', models.CharField(max_length=1000)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basename', models.TextField()),
                ('url', models.TextField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chals.challenge')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeSolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_solve', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chals.challenge')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
