---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: beaverctf-db
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: rctf
      owner: rctf

---
apiVersion: v1
kind: Secret
metadata:
  name: beaverctf-secrets
type: Opaque
stringData:
  # BCTF_DEBUG: False

  BCTF_SECRET_KEY: changemechangeme
  BCTF_ALLOWED_HOSTS: localhost,leafeon.bagel.internal

  BCTF_API_AUTHTOKEN: changeme

  BCTF_CTFTIME_CLIENTID: x
  BCTF_CTFTIME_CLIENTSECRET: x

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: beaverctf-frontend-config
data:
  helm_settings.py: |
    # Add your configuration here

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beaverctf-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beaverctf-frontend
  template:
    metadata:
      labels:
        app: beaverctf-frontend
    spec:
      initContainers:
        - name: migrations
          image: ghcr.io/osusec/beavercds-frontend:main
          command:
            - sh
            - -xc
            - |
              uv run manage.py makemigrations --noinput
              uv run manage.py migrate --noinput
          envFrom:
            - secretRef:
                name: beaverctf-secrets
          # db secrets from CNPG operator
          env: &db_cred_env
            - name: BCTF_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: beaverctf-db-app
                  key: host
            - name: BCTF_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: beaverctf-db-app
                  key: port
            - name: BCTF_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: beaverctf-db-app
                  key: username
            - name: BCTF_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: beaverctf-db-app
                  key: password
            - name: BCTF_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: beaverctf-db-app
                  key: dbname

      containers:
        - name: frontend
          image: ghcr.io/osusec/beavercds-frontend:main
          ports:
            - name: app
              containerPort: 8000
            - name: api
              containerPort: 8001
          envFrom:
            - secretRef:
                name: beaverctf-secrets
          env: *db_cred_env
          volumeMounts:
            - name: config
              mountPath: /app/bctf/helm_settings.py
              subPath: helm_settings.py
      volumes:
        - name: config
          configMap:
            name: beaverctf-frontend-config

---
apiVersion: v1
kind: Service
metadata:
  name: beaverctf-frontend
spec:
  selector:
    app: beaverctf-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beaverctf-frontend
spec:
  rules:
    - host: damctf.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: beaverctf-frontend
                port:
                  number: 80
  tls:
    - hosts:
        - damctf.xyz
      secretName: beaverctf-frontend-tls

---
apiVersion: v1
kind: Service
metadata:
  name: beaverctf-frontend-api
spec:
  selector:
    app: beaverctf-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beaverctf-frontend-api
spec:
  rules:
    - host: damctf.xyz
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: beaverctf-frontend-api
                port:
                  number: 80
  tls:
    - hosts:
        - damctf.xyz
      secretName: beaverctf-frontend-tls
