"""
Django settings for bctf project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from django.urls import reverse_lazy
import datetime as dt
import environ

env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("BCTF_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("BCTF_DEBUG", default=False)

ALLOWED_HOSTS = env.list("BCTF_ALLOWED_HOSTS")

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "account",
    "chals",
    "django.contrib.auth",  # required for resolvestate code, needs to be able to reference the auth_user_model
    "django.contrib.contenttypes",
]

MIDDLEWARE = [
    "bctf-api.middleware.AuthorizationTokenMiddleware",
]

AUTHORIZATION_TOKEN = env.str("BCTF_API_AUTHTOKEN")

AUTH_USER_MODEL = "account.CTFTeam"

ROOT_URLCONF = "bctf-api.urls"

WSGI_APPLICATION = "bctf.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env.str("BCTF_DB_NAME", default="bctf"),
        "USER": env.str("BCTF_DB_USERNAME", default="postgres"),
        "PASSWORD": env.str("BCTF_DB_PASSWORD"),
        "HOST": env.str("BCTF_DB_HOST"),
        "PORT": env.str("BCTF_DB_PORT", default=""),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
