apiVersion: v1
kind: Secret
type: Opaque

metadata:
  name: {{ include "beavercds-frontend.fullname" . }}-admin-credentials
  labels:
    {{- include "beavercds-frontend.labels" . | nindent 4 }}

stringData:
  DJANGO_ADMIN_USERNAME: {{ .Values.init }}
  DJANGO_ADMIN_PASSWORD: {{ .Values.init }}
