apiVersion: v1
kind: Service
metadata:
  name: {{ include "beavercds-frontend.fullname" . }}
  labels:
    {{- include "beavercds-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: frontend
      targetPort: frontend
      protocol: TCP
  selector:
    {{- include "beavercds-frontend.selectorLabels" . | nindent 4 }}
