apiVersion: v1
kind: Service
metadata:
  name: {{ include "beavercds-frontend.fullname" . }}
  labels:
    {{- include "beavercds-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      name: frontend
      targetPort: 8000
      protocol: TCP
    - port: 8001
      name: frontend-api
      targetPort: 8001
      protocol: TCP
  selector:
    {{- include "beavercds-frontend.selectorLabels" . | nindent 4 }}
